### ISSUE TITLE
Arpeggio gives "selection empty" or error for residue with no side-chain

### ISSUE THREAD

**Issue by mariaangelesjs** [harryjubb/arpeggio#15]
Hi Harry,
I am trying to select a residue with no chain (//ALA`24/CA), but when I try to calculate the interactions with arpeggio, it gives me this output:

`docker run --rm -v directory-path -u XXXX:XXXX -it arpeggio python arpeggio.py /XXXX.pdb -s /0/24/ -v`
> INFO//12:09:16.966//Program begin.
> INFO//12:09:17.017//Loaded PDB structure (BioPython)
> INFO//12:09:17.078//Loaded PDB structure (OpenBabel)
> INFO//12:09:17.093//Mapped OB to BioPython atoms and vice-versa.
> INFO//12:09:17.250//Added hydrogens.
> INFO//12:09:17.480//Typed atoms.
> INFO//12:09:17.498//Determined atom explicit and implicit valences, bond orders, atomic numbers, formal charge and number of bound hydrogens.
> INFO//12:09:17.537//Initialised SIFts.
> INFO//12:09:17.545//Determined polypeptide residues, chain breaks, termini
> INFO//12:09:18.044//Percieved and stored rings.
> INFO//12:09:18.071//Perceived and stored amide groups.
> INFO//12:09:18.106//Added hydrogens to BioPython atoms.
> INFO//12:09:18.115//Added VdW radii.
> INFO//12:09:18.123//Added covalent radii.
> INFO//12:09:18.128//Completed NeighborSearch.
> INFO//12:09:18.132//Assigned rings to residues.
> ERROR//12:09:18.135//Selection was empty.
> 

I've tried with `-s //24/` and it gave me this:

> INFO//12:10:45.387//Program begin.
> INFO//12:10:45.444//Loaded PDB structure (BioPython)
> INFO//12:10:45.504//Loaded PDB structure (OpenBabel)
> INFO//12:10:45.519//Mapped OB to BioPython atoms and vice-versa.
> INFO//12:10:45.675//Added hydrogens.
> INFO//12:10:45.902//Typed atoms.
> INFO//12:10:45.921//Determined atom explicit and implicit valences, bond orders, atomic numbers, formal charge and number of bound hydrogens.
> INFO//12:10:45.959//Initialised SIFts.
> INFO//12:10:45.968//Determined polypeptide residues, chain breaks, termini
> INFO//12:10:46.464//Percieved and stored rings.
> INFO//12:10:46.489//Perceived and stored amide groups.
> INFO//12:10:46.526//Added hydrogens to BioPython atoms.
> INFO//12:10:46.534//Added VdW radii.
> INFO//12:10:46.542//Added covalent radii.
> INFO//12:10:46.546//Completed NeighborSearch.
> INFO//12:10:46.551//Assigned rings to residues.
> ERROR//12:10:46.551//Invalid selector: //24/
> Traceback (most recent call last):
>   File "arpeggio.py", line 1406, in <module>
>     selection = selection_parser(args.selection, entity)
>   File "arpeggio.py", line 187, in selection_parser
>     raise SelectionError(original_selection)
> __main__.SelectionError

I had no issue when I was using arpeggio for a receptor with side-chains.
Do you have any solution for this? 
Kind regards,
Maria

**Comment by mariaangelesjs** [comment]
Hi Harry,
I added the chain with a script and there was no issue. I do have to say that adding '//' does not seem to work when you don't have a chain.
Kind regards,
Maria

**Comment by harryjubb** [comment]
Hi Maria,

`-s //24/` should work, and should select every residue numbered `24`, so this may be a bug.

If you're able to share your PDB, please attach it to this issue, if not I can make some test data. I'll take a look when I have a chance.

**Comment by mariaangelesjs** [comment]
I have another bug, same code `/B/24/` gives me : 

> file "/INTERMEDIATE-CB2/ALAMUT-24.pdb", line 1
    ATOM      1  N   ALA B  24     -10.984  22.232  13.178  1.00  0.00           N
SyntaxError: invalid syntax.

However, syntax is correct.
I had to add B chain for it to be recognised. I can't share the PDB file. But I think the pdb code is 6N4B. I'm working with my research's group data, so that's all I can give.
Kind regards,
Maria
